spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${app-properties.database-name}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

app-properties:
  database-name: ${DB_NAME}
